version: '3.8'
services:
  postgres-db:
    image: postgres:13
    container_name: spring-boot-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"

volumes:
  postgres_data:
